version: 0.2

phases:
  install:
    commands:
      - aws cloudformation package --template-file src/example/nodejs/template.yaml --s3-bucket example-nodejs3 --output-template-file packaged.yaml
artifacts:
  type: zip
  files:
    - packaged.yaml
