version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install
      - pip install --user aws-sam-cli
      # Upgrade AWS CLI to the latest version
      #- pip install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      - npm test
  build:
    commands:
      - sam package --template-file src/example/nodejs/template.yaml --s3-bucket example-nodejs3 --output-template-file src/example/nodejs/packaged.yaml
      # Use AWS SAM to package the application by using AWS CloudFormation
      # - aws s3 cp --recursive public/ s3://example-nodejs3/public/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      #- sed -i -e "s|assets/|$WEBSITE_S3_PREFIX/public/assets/|g" public/index.html
      # - aws cloudformation package --template.yaml template.yaml.yml --s3-bucket aws-codestar-ap-northeast-1-466976862258-example-nodejs-app --output-template.yaml template.yaml-export.yml
  post_build:
    commands:

      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template.yaml-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template.yaml-configuration.json

artifacts:
  type: zip
  files:
    - template.yaml-export.yml
    - template.yaml-configuration.json
